name: Deploy Flask App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the application
        run: |
          mkdir -p build
          cp -r src/templates build/
          cp -r static build/
          cp src/app.py build/
          echo "from flask import Flask, render_template" > build/main.py
          echo "app = Flask(__name__)" >> build/main.py
          echo "app.route('/')(lambda: render_template('index.html'))" >> build/main.py
          echo "if __name__ == '__main__': app.run()" >> build/main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages